# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=100)),
                ('fnlwgt', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('education_num', models.IntegerField()),
                ('martial_status', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
