# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='race',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
